ALTER TABLE rooms ADD COLUMN deleted_at TIMESTAMPTZ;
ALTER TABLE teams ADD COLUMN deleted_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMPTZ;
ALTER TABLE seats ADD COLUMN deleted_at TIMESTAMPTZ;
ALTER TABLE reservations ADD COLUMN deleted_at TIMESTAMPTZ;
ALTER TABLE cross_team_requests ADD COLUMN deleted_at TIMESTAMPTZ;
