/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    post: {
      parameters: {
        body: {
          /** Credentials */
          request: definitions["dto.LoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.LoginResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Unauthorized */
        401: {
          schema: string;
        };
      };
    };
  };
  "/cross-team-requests": {
    get: {
      parameters: {
        query: {
          /** Status (pending/approved/rejected) */
          status: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"][];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Request details */
          request: definitions["dto.CreateCrossTeamRequestRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.CrossTeamRequestResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/cross-team-requests/all": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"][];
        };
      };
    };
  };
  "/cross-team-requests/mine": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"][];
        };
      };
    };
  };
  "/cross-team-requests/pending-by-team": {
    get: {
      parameters: {
        query: {
          /** Team ID */
          team_id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"][];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/cross-team-requests/{id}": {
    get: {
      parameters: {
        path: {
          /** Request ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"];
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
  };
  "/cross-team-requests/{id}/approve": {
    put: {
      parameters: {
        path: {
          /** Request ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
      };
    };
  };
  "/cross-team-requests/{id}/reject": {
    put: {
      parameters: {
        path: {
          /** Request ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.CrossTeamRequestResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
      };
    };
  };
  "/reservations": {
    get: {
      parameters: {
        query: {
          /** Filter by user ID */
          user_id?: string;
          /** Date in YYYY-MM-DD format (defaults to today) */
          date?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.ReservationResponse"][];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Reservation details */
          request: definitions["dto.CreateReservationRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.ReservationResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Unauthorized */
        401: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
        /** Not Found */
        404: {
          schema: string;
        };
        /** Conflict */
        409: {
          schema: string;
        };
        /** Too Many Requests */
        429: {
          schema: string;
        };
      };
    };
  };
  "/reservations/admin": {
    post: {
      parameters: {
        body: {
          /** Admin reservation details */
          request: definitions["dto.AdminCreateReservationRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.ReservationResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Unauthorized */
        401: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
        /** Not Found */
        404: {
          schema: string;
        };
        /** Conflict */
        409: {
          schema: string;
        };
      };
    };
  };
  "/reservations/by-room": {
    get: {
      parameters: {
        query: {
          /** Room ID */
          room_id: string;
          /** Date in YYYY-MM-DD format (defaults to today) */
          date?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.ReservationWithUserResponse"][];
        };
      };
    };
  };
  "/reservations/week": {
    get: {
      parameters: {
        query: {
          /** Date in YYYY-MM-DD format (defaults to today) */
          date?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.ReservationResponse"][];
        };
      };
    };
  };
  "/reservations/{id}": {
    delete: {
      parameters: {
        path: {
          /** Reservation ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DeleteResponse"];
        };
        /** Unauthorized */
        401: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
  };
  "/rooms": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.RoomResponse"][];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Room details */
          request: definitions["dto.CreateRoomRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.RoomResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/rooms/{id}": {
    get: {
      parameters: {
        path: {
          /** Room ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.RoomResponse"];
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
    put: {
      parameters: {
        path: {
          /** Room ID */
          id: string;
        };
        body: {
          /** Room details */
          request: definitions["dto.UpdateRoomRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.RoomResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** Room ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DeleteResponse"];
        };
        /** Internal Server Error */
        500: {
          schema: string;
        };
      };
    };
  };
  "/rooms/{id}/seats": {
    put: {
      parameters: {
        path: {
          /** Room ID */
          id: string;
        };
        body: {
          /** Full seat list */
          request: definitions["dto.BulkSyncSeatsRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.BulkSyncSeatsResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/seats": {
    get: {
      parameters: {
        query: {
          /** Room ID */
          room_id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SeatResponse"][];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Seat details */
          request: definitions["dto.CreateSeatRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.SeatResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/seats/{id}": {
    get: {
      parameters: {
        path: {
          /** Seat ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SeatResponse"];
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** Seat ID */
          id: string;
        };
      };
      responses: {
        /** No Content */
        204: {
          schema: string;
        };
      };
    };
  };
  "/seats/{id}/assign": {
    post: {
      parameters: {
        path: {
          /** Seat ID */
          id: string;
        };
        body: {
          /** User ID to assign */
          request: definitions["dto.AssignSeatRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SeatResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** Seat ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SeatResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
      };
    };
  };
  "/seats/{id}/move": {
    put: {
      parameters: {
        path: {
          /** Seat ID */
          id: string;
        };
        body: {
          /** New position */
          request: definitions["dto.MoveSeatRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.SeatResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/teams": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.TeamResponse"][];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** Team name */
          request: definitions["dto.CreateTeamRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.TeamResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/teams/{id}": {
    get: {
      parameters: {
        path: {
          /** Team ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.TeamResponse"];
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** Team ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DeleteResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Conflict */
        409: {
          schema: string;
        };
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          /** Team ID (omit for all users) */
          team_id?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserResponse"][];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** User details */
          request: definitions["dto.CreateUserRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["dto.UserResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
  "/users/by-email": {
    get: {
      parameters: {
        query: {
          /** User email */
          email: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserResponse"];
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
  };
  "/users/{id}": {
    get: {
      parameters: {
        path: {
          /** User ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserResponse"];
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** User ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.DeleteResponse"];
        };
      };
    };
  };
  "/users/{id}/password": {
    put: {
      parameters: {
        path: {
          /** User ID */
          id: string;
        };
        body: {
          /** New password */
          request: definitions["dto.SetPasswordRequest"];
        };
      };
      responses: {
        /** No Content */
        204: {
          schema: string;
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Unauthorized */
        401: {
          schema: string;
        };
      };
    };
  };
  "/users/{id}/role": {
    put: {
      parameters: {
        path: {
          /** User ID */
          id: string;
        };
        body: {
          /** New role */
          request: definitions["dto.UpdateUserRoleRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
  };
  "/users/{id}/team": {
    put: {
      parameters: {
        path: {
          /** User ID */
          id: string;
        };
        body: {
          /** Team ID (null to remove) */
          request: definitions["dto.UpdateUserTeamRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["dto.UserResponse"];
        };
        /** Bad Request */
        400: {
          schema: string;
        };
        /** Forbidden */
        403: {
          schema: string;
        };
        /** Not Found */
        404: {
          schema: string;
        };
      };
    };
  };
  "/users/{id}/weekly-limit": {
    put: {
      parameters: {
        path: {
          /** User ID */
          id: string;
        };
        body: {
          /** Weekly limit */
          request: definitions["dto.UpdateWeeklyLimitRequest"];
        };
      };
      responses: {
        /** No Content */
        204: {
          schema: string;
        };
        /** Bad Request */
        400: {
          schema: string;
        };
      };
    };
  };
}

export interface definitions {
  "dto.AdminCreateReservationRequest": {
    date?: string;
    seat_id?: string;
    user_id?: string;
  };
  "dto.AssignSeatRequest": {
    user_id?: string;
  };
  "dto.BulkSeatItem": {
    id?: string;
    label?: string;
    pos_x?: number;
    pos_y?: number;
    team_id?: string;
  };
  "dto.BulkSyncSeatsRequest": {
    seats?: definitions["dto.BulkSeatItem"][];
  };
  "dto.BulkSyncSeatsResponse": {
    seats?: definitions["dto.SeatResponse"][];
  };
  "dto.CreateCrossTeamRequestRequest": {
    /** @description YYYY-MM-DD */
    date?: string;
    target_seat_id?: string;
  };
  "dto.CreateReservationRequest": {
    /** @description YYYY-MM-DD */
    date?: string;
    seat_id?: string;
  };
  "dto.CreateRoomRequest": {
    grid_height?: number;
    grid_width?: number;
    name?: string;
  };
  "dto.CreateSeatRequest": {
    label?: string;
    pos_x?: number;
    pos_y?: number;
    room_id?: string;
    team_id?: string;
  };
  "dto.CreateTeamRequest": {
    name?: string;
  };
  "dto.CreateUserRequest": {
    email?: string;
    name?: string;
    role?: string;
    team_id?: string;
    weekly_limit?: number;
  };
  "dto.CrossTeamRequestResponse": {
    date?: string;
    id?: string;
    requesting_user_id?: string;
    status?: string;
    target_seat_id?: string;
  };
  "dto.DeleteResponse": {
    deleted?: boolean;
    seats_deleted?: number;
  };
  "dto.LoginRequest": {
    password?: string;
    username?: string;
  };
  "dto.LoginResponse": {
    token?: string;
    user?: definitions["dto.UserResponse"];
  };
  "dto.MoveSeatRequest": {
    pos_x?: number;
    pos_y?: number;
  };
  "dto.ReservationResponse": {
    date?: string;
    id?: string;
    seat_id?: string;
    user_id?: string;
  };
  "dto.ReservationWithUserResponse": {
    date?: string;
    id?: string;
    seat_id?: string;
    seat_label?: string;
    user_id?: string;
    user_name?: string;
  };
  "dto.RoomResponse": {
    created_at?: string;
    grid_height?: number;
    grid_width?: number;
    id?: string;
    name?: string;
    updated_at?: string;
  };
  "dto.SeatResponse": {
    assigned_user_id?: string;
    assigned_user_name?: string;
    id?: string;
    label?: string;
    pos_x?: number;
    pos_y?: number;
    room_id?: string;
    team_id?: string;
  };
  "dto.SetPasswordRequest": {
    password?: string;
  };
  "dto.TeamResponse": {
    id?: string;
    name?: string;
  };
  "dto.UpdateRoomRequest": {
    grid_height?: number;
    grid_width?: number;
    name?: string;
  };
  "dto.UpdateUserRoleRequest": {
    role?: string;
  };
  "dto.UpdateUserTeamRequest": {
    team_id?: string;
  };
  "dto.UpdateWeeklyLimitRequest": {
    weekly_limit?: number;
  };
  "dto.UserResponse": {
    email?: string;
    id?: string;
    name?: string;
    role?: string;
    team_id?: string;
    weekly_limit?: number;
  };
}

export interface operations {}

export interface external {}
