// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cross_team_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCrossTeamRequest = `-- name: CreateCrossTeamRequest :one
INSERT INTO cross_team_requests (requesting_user_id, target_seat_id, date)
VALUES ($1, $2, $3)
RETURNING id, requesting_user_id, target_seat_id, date, status, created_at, updated_at
`

type CreateCrossTeamRequestParams struct {
	RequestingUserID uuid.UUID   `db:"requesting_user_id" json:"requesting_user_id"`
	TargetSeatID     uuid.UUID   `db:"target_seat_id" json:"target_seat_id"`
	Date             pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) CreateCrossTeamRequest(ctx context.Context, arg CreateCrossTeamRequestParams) (CrossTeamRequest, error) {
	row := q.db.QueryRow(ctx, createCrossTeamRequest, arg.RequestingUserID, arg.TargetSeatID, arg.Date)
	var i CrossTeamRequest
	err := row.Scan(
		&i.ID,
		&i.RequestingUserID,
		&i.TargetSeatID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCrossTeamRequestByID = `-- name: GetCrossTeamRequestByID :one
SELECT id, requesting_user_id, target_seat_id, date, status, created_at, updated_at FROM cross_team_requests WHERE id = $1
`

func (q *Queries) GetCrossTeamRequestByID(ctx context.Context, id uuid.UUID) (CrossTeamRequest, error) {
	row := q.db.QueryRow(ctx, getCrossTeamRequestByID, id)
	var i CrossTeamRequest
	err := row.Scan(
		&i.ID,
		&i.RequestingUserID,
		&i.TargetSeatID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrossTeamRequestsByStatus = `-- name: ListCrossTeamRequestsByStatus :many
SELECT id, requesting_user_id, target_seat_id, date, status, created_at, updated_at FROM cross_team_requests WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCrossTeamRequestsByStatus(ctx context.Context, status string) ([]CrossTeamRequest, error) {
	rows, err := q.db.Query(ctx, listCrossTeamRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrossTeamRequest
	for rows.Next() {
		var i CrossTeamRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestingUserID,
			&i.TargetSeatID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsForTeam = `-- name: ListPendingRequestsForTeam :many
SELECT ctr.id, ctr.requesting_user_id, ctr.target_seat_id, ctr.date, ctr.status, ctr.created_at, ctr.updated_at FROM cross_team_requests ctr
JOIN seats s ON ctr.target_seat_id = s.id
JOIN teams t ON s.team_id = t.id
WHERE t.id = $1 AND ctr.status = 'pending'
ORDER BY ctr.created_at DESC
`

func (q *Queries) ListPendingRequestsForTeam(ctx context.Context, id uuid.UUID) ([]CrossTeamRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsForTeam, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrossTeamRequest
	for rows.Next() {
		var i CrossTeamRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestingUserID,
			&i.TargetSeatID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrossTeamRequestStatus = `-- name: UpdateCrossTeamRequestStatus :one
UPDATE cross_team_requests
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, requesting_user_id, target_seat_id, date, status, created_at, updated_at
`

type UpdateCrossTeamRequestStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateCrossTeamRequestStatus(ctx context.Context, arg UpdateCrossTeamRequestStatusParams) (CrossTeamRequest, error) {
	row := q.db.QueryRow(ctx, updateCrossTeamRequestStatus, arg.ID, arg.Status)
	var i CrossTeamRequest
	err := row.Scan(
		&i.ID,
		&i.RequestingUserID,
		&i.TargetSeatID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
