// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CrossTeamRequest struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	RequestingUserID uuid.UUID          `db:"requesting_user_id" json:"requesting_user_id"`
	TargetSeatID     uuid.UUID          `db:"target_seat_id" json:"target_seat_id"`
	Date             pgtype.Date        `db:"date" json:"date"`
	Status           string             `db:"status" json:"status"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time          `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Reservation struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	SeatID    uuid.UUID          `db:"seat_id" json:"seat_id"`
	Date      pgtype.Date        `db:"date" json:"date"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Room struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	GridWidth  int32              `db:"grid_width" json:"grid_width"`
	GridHeight int32              `db:"grid_height" json:"grid_height"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time          `db:"updated_at" json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Seat struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	RoomID         uuid.UUID          `db:"room_id" json:"room_id"`
	TeamID         uuid.UUID          `db:"team_id" json:"team_id"`
	Label          string             `db:"label" json:"label"`
	PosX           int32              `db:"pos_x" json:"pos_x"`
	PosY           int32              `db:"pos_y" json:"pos_y"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time          `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AssignedUserID pgtype.UUID        `db:"assigned_user_id" json:"assigned_user_id"`
}

type Team struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Email        pgtype.Text        `db:"email" json:"email"`
	TeamID       pgtype.UUID        `db:"team_id" json:"team_id"`
	Role         string             `db:"role" json:"role"`
	WeeklyLimit  int32              `db:"weekly_limit" json:"weekly_limit"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time          `db:"updated_at" json:"updated_at"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
