// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReservationsByUserInWeek = `-- name: CountReservationsByUserInWeek :one
SELECT COUNT(*)::int AS count
FROM reservations
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
  AND deleted_at IS NULL
`

type CountReservationsByUserInWeekParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) CountReservationsByUserInWeek(ctx context.Context, arg CountReservationsByUserInWeekParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReservationsByUserInWeek, arg.UserID, arg.Date, arg.Date_2)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (user_id, seat_id, date)
VALUES ($1, $2, $3)
RETURNING id, user_id, seat_id, date, created_at, deleted_at
`

type CreateReservationParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	SeatID uuid.UUID   `db:"seat_id" json:"seat_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation, arg.UserID, arg.SeatID, arg.Date)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Date,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, user_id, seat_id, date, created_at, deleted_at FROM reservations WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Date,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationBySeatAndDate = `-- name: GetReservationBySeatAndDate :one
SELECT id, user_id, seat_id, date, created_at, deleted_at FROM reservations WHERE seat_id = $1 AND date = $2 AND deleted_at IS NULL
`

type GetReservationBySeatAndDateParams struct {
	SeatID uuid.UUID   `db:"seat_id" json:"seat_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetReservationBySeatAndDate(ctx context.Context, arg GetReservationBySeatAndDateParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationBySeatAndDate, arg.SeatID, arg.Date)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Date,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReservationsByDate = `-- name: ListReservationsByDate :many
SELECT id, user_id, seat_id, date, created_at, deleted_at FROM reservations WHERE date = $1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListReservationsByDate(ctx context.Context, date pgtype.Date) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.Date,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByRoomAndDate = `-- name: ListReservationsByRoomAndDate :many
SELECT r.id, r.user_id, r.seat_id, r.date, r.created_at, r.deleted_at FROM reservations r
JOIN seats s ON r.seat_id = s.id
WHERE s.room_id = $1 AND r.date = $2 AND r.deleted_at IS NULL
ORDER BY r.created_at
`

type ListReservationsByRoomAndDateParams struct {
	RoomID uuid.UUID   `db:"room_id" json:"room_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) ListReservationsByRoomAndDate(ctx context.Context, arg ListReservationsByRoomAndDateParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByRoomAndDate, arg.RoomID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.Date,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByRoomAndDateWithDetails = `-- name: ListReservationsByRoomAndDateWithDetails :many
SELECT r.id, r.user_id, u.name as user_name, r.seat_id, s.label as seat_label, r.date
FROM reservations r
JOIN seats s ON r.seat_id = s.id
JOIN users u ON r.user_id = u.id
WHERE s.room_id = $1 AND r.date = $2 AND r.deleted_at IS NULL
ORDER BY r.created_at
`

type ListReservationsByRoomAndDateWithDetailsParams struct {
	RoomID uuid.UUID   `db:"room_id" json:"room_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

type ListReservationsByRoomAndDateWithDetailsRow struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	UserName  string      `db:"user_name" json:"user_name"`
	SeatID    uuid.UUID   `db:"seat_id" json:"seat_id"`
	SeatLabel string      `db:"seat_label" json:"seat_label"`
	Date      pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) ListReservationsByRoomAndDateWithDetails(ctx context.Context, arg ListReservationsByRoomAndDateWithDetailsParams) ([]ListReservationsByRoomAndDateWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByRoomAndDateWithDetails, arg.RoomID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsByRoomAndDateWithDetailsRow
	for rows.Next() {
		var i ListReservationsByRoomAndDateWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.SeatID,
			&i.SeatLabel,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserAndDate = `-- name: ListReservationsByUserAndDate :many
SELECT id, user_id, seat_id, date, created_at, deleted_at FROM reservations WHERE user_id = $1 AND date = $2 AND deleted_at IS NULL ORDER BY created_at
`

type ListReservationsByUserAndDateParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) ListReservationsByUserAndDate(ctx context.Context, arg ListReservationsByUserAndDateParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserAndDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.Date,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserAndWeek = `-- name: ListReservationsByUserAndWeek :many
SELECT id, user_id, seat_id, date, created_at, deleted_at FROM reservations
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
  AND deleted_at IS NULL
ORDER BY date
`

type ListReservationsByUserAndWeekParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListReservationsByUserAndWeek(ctx context.Context, arg ListReservationsByUserAndWeekParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserAndWeek, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.Date,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteReservation = `-- name: SoftDeleteReservation :exec
UPDATE reservations SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteReservation, id)
	return err
}
