// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReservationsByUserInWeek = `-- name: CountReservationsByUserInWeek :one
SELECT COUNT(*)::int AS count
FROM reservations
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
`

type CountReservationsByUserInWeekParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) CountReservationsByUserInWeek(ctx context.Context, arg CountReservationsByUserInWeekParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReservationsByUserInWeek, arg.UserID, arg.Date, arg.Date_2)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (user_id, seat_id, date)
VALUES ($1, $2, $3)
RETURNING id, user_id, seat_id, date, created_at
`

type CreateReservationParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	SeatID uuid.UUID   `db:"seat_id" json:"seat_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation, arg.UserID, arg.SeatID, arg.Date)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations WHERE id = $1
`

func (q *Queries) DeleteReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservation, id)
	return err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, user_id, seat_id, date, created_at FROM reservations WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getReservationBySeatAndDate = `-- name: GetReservationBySeatAndDate :one
SELECT id, user_id, seat_id, date, created_at FROM reservations WHERE seat_id = $1 AND date = $2
`

type GetReservationBySeatAndDateParams struct {
	SeatID uuid.UUID   `db:"seat_id" json:"seat_id"`
	Date   pgtype.Date `db:"date" json:"date"`
}

func (q *Queries) GetReservationBySeatAndDate(ctx context.Context, arg GetReservationBySeatAndDateParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationBySeatAndDate, arg.SeatID, arg.Date)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const listReservationsByUserAndWeek = `-- name: ListReservationsByUserAndWeek :many
SELECT id, user_id, seat_id, date, created_at FROM reservations
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date
`

type ListReservationsByUserAndWeekParams struct {
	UserID uuid.UUID   `db:"user_id" json:"user_id"`
	Date   pgtype.Date `db:"date" json:"date"`
	Date_2 pgtype.Date `db:"date_2" json:"date_2"`
}

func (q *Queries) ListReservationsByUserAndWeek(ctx context.Context, arg ListReservationsByUserAndWeekParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserAndWeek, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
