// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, grid_width, grid_height)
VALUES ($1, $2, $3)
RETURNING id, name, grid_width, grid_height, created_at, updated_at
`

type CreateRoomParams struct {
	Name       string `db:"name" json:"name"`
	GridWidth  int32  `db:"grid_width" json:"grid_width"`
	GridHeight int32  `db:"grid_height" json:"grid_height"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.GridWidth, arg.GridHeight)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GridWidth,
		&i.GridHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, grid_width, grid_height, created_at, updated_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GridWidth,
		&i.GridHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, grid_width, grid_height, created_at, updated_at FROM rooms ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GridWidth,
			&i.GridHeight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $2, grid_width = $3, grid_height = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, grid_width, grid_height, created_at, updated_at
`

type UpdateRoomParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Name       string    `db:"name" json:"name"`
	GridWidth  int32     `db:"grid_width" json:"grid_width"`
	GridHeight int32     `db:"grid_height" json:"grid_height"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.GridWidth,
		arg.GridHeight,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GridWidth,
		&i.GridHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
