// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (room_id, team_id, label, pos_x, pos_y, rotation)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, room_id, team_id, label, pos_x, pos_y, rotation, created_at, updated_at
`

type CreateSeatParams struct {
	RoomID   uuid.UUID `db:"room_id" json:"room_id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Label    string    `db:"label" json:"label"`
	PosX     int32     `db:"pos_x" json:"pos_x"`
	PosY     int32     `db:"pos_y" json:"pos_y"`
	Rotation int32     `db:"rotation" json:"rotation"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.RoomID,
		arg.TeamID,
		arg.Label,
		arg.PosX,
		arg.PosY,
		arg.Rotation,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.Rotation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeat = `-- name: DeleteSeat :exec
DELETE FROM seats WHERE id = $1
`

func (q *Queries) DeleteSeat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeat, id)
	return err
}

const getSeatByID = `-- name: GetSeatByID :one
SELECT id, room_id, team_id, label, pos_x, pos_y, rotation, created_at, updated_at FROM seats WHERE id = $1
`

func (q *Queries) GetSeatByID(ctx context.Context, id uuid.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, getSeatByID, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.Rotation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeatsByRoom = `-- name: ListSeatsByRoom :many
SELECT id, room_id, team_id, label, pos_x, pos_y, rotation, created_at, updated_at FROM seats WHERE room_id = $1 ORDER BY pos_y, pos_x
`

func (q *Queries) ListSeatsByRoom(ctx context.Context, roomID uuid.UUID) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listSeatsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seat
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.TeamID,
			&i.Label,
			&i.PosX,
			&i.PosY,
			&i.Rotation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeat = `-- name: UpdateSeat :one
UPDATE seats
SET label = $2, pos_x = $3, pos_y = $4, rotation = $5, updated_at = now()
WHERE id = $1
RETURNING id, room_id, team_id, label, pos_x, pos_y, rotation, created_at, updated_at
`

type UpdateSeatParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Label    string    `db:"label" json:"label"`
	PosX     int32     `db:"pos_x" json:"pos_x"`
	PosY     int32     `db:"pos_y" json:"pos_y"`
	Rotation int32     `db:"rotation" json:"rotation"`
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, updateSeat,
		arg.ID,
		arg.Label,
		arg.PosX,
		arg.PosY,
		arg.Rotation,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.Rotation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSeatFull = `-- name: UpdateSeatFull :one
UPDATE seats
SET label = $2, team_id = $3, pos_x = $4, pos_y = $5, rotation = $6, updated_at = now()
WHERE id = $1
RETURNING id, room_id, team_id, label, pos_x, pos_y, rotation, created_at, updated_at
`

type UpdateSeatFullParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Label    string    `db:"label" json:"label"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	PosX     int32     `db:"pos_x" json:"pos_x"`
	PosY     int32     `db:"pos_y" json:"pos_y"`
	Rotation int32     `db:"rotation" json:"rotation"`
}

func (q *Queries) UpdateSeatFull(ctx context.Context, arg UpdateSeatFullParams) (Seat, error) {
	row := q.db.QueryRow(ctx, updateSeatFull,
		arg.ID,
		arg.Label,
		arg.TeamID,
		arg.PosX,
		arg.PosY,
		arg.Rotation,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.Rotation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
