// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignSeat = `-- name: AssignSeat :one
UPDATE seats SET assigned_user_id = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id
`

type AssignSeatParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	AssignedUserID pgtype.UUID `db:"assigned_user_id" json:"assigned_user_id"`
}

func (q *Queries) AssignSeat(ctx context.Context, arg AssignSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, assignSeat, arg.ID, arg.AssignedUserID)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (room_id, team_id, label, pos_x, pos_y, assigned_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id
`

type CreateSeatParams struct {
	RoomID         uuid.UUID   `db:"room_id" json:"room_id"`
	TeamID         uuid.UUID   `db:"team_id" json:"team_id"`
	Label          string      `db:"label" json:"label"`
	PosX           int32       `db:"pos_x" json:"pos_x"`
	PosY           int32       `db:"pos_y" json:"pos_y"`
	AssignedUserID pgtype.UUID `db:"assigned_user_id" json:"assigned_user_id"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.RoomID,
		arg.TeamID,
		arg.Label,
		arg.PosX,
		arg.PosY,
		arg.AssignedUserID,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}

const getSeatByAssignedUser = `-- name: GetSeatByAssignedUser :one
SELECT id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id FROM seats WHERE assigned_user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSeatByAssignedUser(ctx context.Context, assignedUserID pgtype.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, getSeatByAssignedUser, assignedUserID)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}

const getSeatByID = `-- name: GetSeatByID :one
SELECT id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id FROM seats WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSeatByID(ctx context.Context, id uuid.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, getSeatByID, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}

const listSeatsByRoom = `-- name: ListSeatsByRoom :many
SELECT id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id FROM seats WHERE room_id = $1 AND deleted_at IS NULL ORDER BY pos_y, pos_x
`

func (q *Queries) ListSeatsByRoom(ctx context.Context, roomID uuid.UUID) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listSeatsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seat
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.TeamID,
			&i.Label,
			&i.PosX,
			&i.PosY,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AssignedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSeat = `-- name: SoftDeleteSeat :exec
UPDATE seats SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteSeat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSeat, id)
	return err
}

const softDeleteSeatsByRoom = `-- name: SoftDeleteSeatsByRoom :exec
UPDATE seats SET deleted_at = now() WHERE room_id = $1
`

func (q *Queries) SoftDeleteSeatsByRoom(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSeatsByRoom, roomID)
	return err
}

const unassignSeat = `-- name: UnassignSeat :one
UPDATE seats SET assigned_user_id = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id
`

func (q *Queries) UnassignSeat(ctx context.Context, id uuid.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, unassignSeat, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}

const updateSeat = `-- name: UpdateSeat :one
UPDATE seats
SET label = $2, pos_x = $3, pos_y = $4, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id
`

type UpdateSeatParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Label string    `db:"label" json:"label"`
	PosX  int32     `db:"pos_x" json:"pos_x"`
	PosY  int32     `db:"pos_y" json:"pos_y"`
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, updateSeat,
		arg.ID,
		arg.Label,
		arg.PosX,
		arg.PosY,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}

const updateSeatFull = `-- name: UpdateSeatFull :one
UPDATE seats
SET label = $2, team_id = $3, pos_x = $4, pos_y = $5, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, room_id, team_id, label, pos_x, pos_y, created_at, updated_at, deleted_at, assigned_user_id
`

type UpdateSeatFullParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Label  string    `db:"label" json:"label"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	PosX   int32     `db:"pos_x" json:"pos_x"`
	PosY   int32     `db:"pos_y" json:"pos_y"`
}

func (q *Queries) UpdateSeatFull(ctx context.Context, arg UpdateSeatFullParams) (Seat, error) {
	row := q.db.QueryRow(ctx, updateSeatFull,
		arg.ID,
		arg.Label,
		arg.TeamID,
		arg.PosX,
		arg.PosY,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TeamID,
		&i.Label,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AssignedUserID,
	)
	return i, err
}
