// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, team_id, role, weekly_limit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, team_id, role, weekly_limit, created_at, updated_at
`

type CreateUserParams struct {
	Name        string      `db:"name" json:"name"`
	Email       string      `db:"email" json:"email"`
	TeamID      pgtype.UUID `db:"team_id" json:"team_id"`
	Role        string      `db:"role" json:"role"`
	WeeklyLimit int32       `db:"weekly_limit" json:"weekly_limit"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.TeamID,
		arg.Role,
		arg.WeeklyLimit,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TeamID,
		&i.Role,
		&i.WeeklyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, team_id, role, weekly_limit, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TeamID,
		&i.Role,
		&i.WeeklyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, team_id, role, weekly_limit, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TeamID,
		&i.Role,
		&i.WeeklyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, team_id, role, weekly_limit, created_at, updated_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.TeamID,
			&i.Role,
			&i.WeeklyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTeam = `-- name: ListUsersByTeam :many
SELECT id, name, email, team_id, role, weekly_limit, created_at, updated_at FROM users WHERE team_id = $1 ORDER BY name
`

func (q *Queries) ListUsersByTeam(ctx context.Context, teamID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.TeamID,
			&i.Role,
			&i.WeeklyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserWeeklyLimit = `-- name: UpdateUserWeeklyLimit :one
UPDATE users SET weekly_limit = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, email, team_id, role, weekly_limit, created_at, updated_at
`

type UpdateUserWeeklyLimitParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	WeeklyLimit int32     `db:"weekly_limit" json:"weekly_limit"`
}

func (q *Queries) UpdateUserWeeklyLimit(ctx context.Context, arg UpdateUserWeeklyLimitParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserWeeklyLimit, arg.ID, arg.WeeklyLimit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TeamID,
		&i.Role,
		&i.WeeklyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
